In [19]:
#Importing libraries
!pip install pyspark
import pandas as pd
from pyspark.sql import sparksession
from pyspark.sql.functions import*

Requirement already satisfied: pyspark in c:\users\sukan\anaconda3\lib\site-packages (3.5.3)
Requirement already satisfied: py4j==0.10.9.7 in c:\users\sukan\anaconda3\lib\site-packages (from pyspark) (0.10.9.7)

ImportError: cannot import name 'sparksession' from 'pyspark.sql' (C:\Users\sukan\anaconda3\Lib\site-packages\pyspark\sql\__init__.py)

In [28]:
# loding the csv files in to data frames 
df21 = pd.read_csv(r"C:\Users\sukan\OneDrive\Documents\Masters\Projects\CARS.csv")
df22 = pd.read_csv(r"C:\Users\sukan\OneDrive\Documents\Masters\Projects\CUSTOMERS.csv")
df23 = pd.read_csv(r"C:\Users\sukan\OneDrive\Documents\Masters\Projects\HOUSEHOLDS.csv")

In [30]:
#pre-view of CARS data
df21.head()

,CAR_ID,Status,State,Model Year,Make,Body Style,Vehicle Value,Annual Miles Driven,Business Use,Antique Vehicle,Lien,Lease,Driver Safety Discount,Vehicle Safety Discount,Claim Payout,6 Month Premium Amount
0,844435,In Force,OK,1990,Manufacturer7,4 door,50000.00,56,0,1,1,0,0,1,0,42.890000
1,410619,In Force,OK,2019,Manufacturer5,SUV,8151.75,12136,0,0,0,1,0,1,0,58.887695
2,192812,In Force,OK,2008,Manufacturer2,SUV,1651.20,14674,0,0,1,0,0,1,0,322.307381
3,752033,In Force,OK,1973,Manufacturer2,Truck,500.00,15762,0,0,1,0,0,0,0,232.670242
4,23783,In Force,NY,2022,Manufacturer3,SUV,18873.90,10154,0,0,1,0,0,1,0,167.432014

In [32]:
#pre-view of CUSTOMERS data
df22.head()

,CUST_ID,Date of Birth,Marital Status,Employment Type,Income,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,801198110,11/6/02,D,Student,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,281855167,6/23/55,D,Retired,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,688373183,8/16/96,M,Office and Administrative Support,42052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,752746800,8/22/36,M,Retired,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,114187354,3/18/08,D,Sales and Related,60879,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
#pre-view of HOUSEHOLDS data
df23.head()

,HH_ID,CUST_ID,CAR_ID,Active HH,HH Start Date,Phone Number,ZIP,State,Country,Referral Source
0,219790301,801198110,844435,1,11/18/22,(709) 379-9036,70442,OK,USA,Other
1,219790301,281855167,410619,1,11/18/22,(740) 565-4060,70442,OK,USA,Other
2,219790301,688373183,192812,1,11/18/22,(117) 457-9582,70442,OK,USA,Other
3,219790301,752746800,752033,1,11/18/22,(536) 797-5920,70442,OK,USA,Other
4,464806390,114187354,23783,1,10/9/20,(152) 373-1773,42706,NY,USA,Event

In [36]:
#combining the data.
combined_df = pd.merge(df23, df22, on='CUST_ID')
combined_df = pd.merge(combined_df, df21, on='CAR_ID')
combined_df.head()

,HH_ID,CUST_ID,CAR_ID,Active HH,HH Start Date,Phone Number,ZIP,State_x,Country,Referral Source,...,Vehicle Value,Annual Miles Driven,Business Use,Antique Vehicle,Lien,Lease,Driver Safety Discount,Vehicle Safety Discount,Claim Payout,6 Month Premium Amount
0,219790301,801198110,844435,1,11/18/22,(709) 379-9036,70442,OK,USA,Other,...,50000.00,56,0,1,1,0,0,1,0,42.890000
1,219790301,801198110,844435,1,11/18/22,(709) 379-9036,70442,OK,USA,Other,...,500.00,14800,0,0,1,0,0,0,0,452.814770
2,219790301,801198110,844435,1,11/18/22,(709) 379-9036,70442,OK,USA,Other,...,500.00,8439,0,0,0,0,0,0,0,380.678401
3,219790301,281855167,410619,1,11/18/22,(740) 565-4060,70442,OK,USA,Other,...,8151.75,12136,0,0,0,1,0,1,0,58.887695
4,219790301,281855167,410619,1,11/18/22,(740) 565-4060,70442,OK,USA,Other,...,13460.60,89619,0,0,0,0,0,1,0,336.262875

In [40]:
pd.set_option('display.max_columns', None)  # Show all columns
print(combined_df.head())

       HH_ID    CUST_ID  CAR_ID  Active HH HH Start Date    Phone Number  \
0  219790301  801198110  844435          1      11/18/22  (709) 379-9036
1  219790301  801198110  844435          1      11/18/22  (709) 379-9036
2  219790301  801198110  844435          1      11/18/22  (709) 379-9036
3  219790301  281855167  410619          1      11/18/22  (740) 565-4060
4  219790301  281855167  410619          1      11/18/22  (740) 565-4060

    ZIP  State_x Country Referral Source Date of Birth Marital Status  \
0  70442      OK     USA           Other       11/6/02              D
1  70442      OK     USA           Other       11/6/02              D
2  70442      OK     USA           Other       11/6/02              D
3  70442      OK     USA           Other       6/23/55              D
4  70442      OK     USA           Other       6/23/55              D

  Employment Type Income  Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  \
0         Student      0         NaN         NaN         NaN         NaN
1         Student      0         NaN         NaN         NaN         NaN
2         Student      0         NaN         NaN         NaN         NaN
3         Retired      0         NaN         NaN         NaN         NaN
4         Retired      0         NaN         NaN         NaN         NaN

   Unnamed: 9  Unnamed: 10  Unnamed: 11  Unnamed: 12  Unnamed: 13  \
0         NaN          NaN          NaN          NaN          NaN
1         NaN          NaN          NaN          NaN          NaN
2         NaN          NaN          NaN          NaN          NaN
3         NaN          NaN          NaN          NaN          NaN
4         NaN          NaN          NaN          NaN          NaN

   Unnamed: 14  Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18  \
0          NaN          NaN          NaN          NaN          NaN
1          NaN          NaN          NaN          NaN          NaN
2          NaN          NaN          NaN          NaN          NaN
3          NaN          NaN          NaN          NaN          NaN
4          NaN          NaN          NaN          NaN          NaN

   Unnamed: 19                 Status State_y  Model Year           Make  \
0          NaN               In Force      OK        1990  Manufacturer7
1          NaN               In Force      AL        1955  Manufacturer2
2          NaN  Customer Cancellation      OH        1973  Manufacturer2
3          NaN               In Force      OK        2019  Manufacturer5
4          NaN               In Force      GA        2021  Manufacturer3

  Body Style  Vehicle Value  Annual Miles Driven  Business Use  \
0     4 door       50000.00                   56             0
1     4 door         500.00                14800             0
2        SUV         500.00                 8439             0
3        SUV        8151.75                12136             0
4        SUV       13460.60                89619             0

   Antique Vehicle  Lien  Lease  Driver Safety Discount  \
0                1     1      0                       0
1                0     1      0                       0
2                0     0      0                       0
3                0     0      1                       0
4                0     0      0                       0

   Vehicle Safety Discount  Claim Payout  6 Month Premium Amount
0                        1             0               42.890000
1                        0             0              452.814770
2                        0             0              380.678401
3                        1             0               58.887695
4                        1             0              336.262875

In [48]:
#removing all the unnecessary columns above seen in the data frame
combined_df= combined_df.drop(columns=[col for col in combined_df.columns if "Unnamed" in col])

In [50]:
#Data cleaning checklist
#1. check for Nan  Values
print("Checking for missing values in each column:")
print(combined_df.isnull().sum())

Checking for missing values in each column:
HH_ID                      0
CUST_ID                    0
CAR_ID                     0
Active HH                  0
HH Start Date              0
Phone Number               0
ZIP                        0
State_x                    0
Country                    0
Referral Source            0
Date of Birth              0
Marital Status             0
Employment Type            0
Income                     0
Status                     0
State_y                    0
Model Year                 0
Make                       0
Body Style                 0
Vehicle Value              0
Annual Miles Driven        0
Business Use               0
Antique Vehicle            0
Lien                       0
Lease                      0
Driver Safety Discount     0
Vehicle Safety Discount    0
Claim Payout               0
6 Month Premium Amount     0
dtype: int64

In [54]:
#Data cleaning checklist
#2. Check for Duplicate Rows:

print(f"Number of duplicate rows: {combined_df.duplicated().sum()}")  # Count duplicates

Number of duplicate rows: 0

In [56]:
#Data cleaning checklist
#3. Check for Data Type Mismatches
print("Data types before conversion:")
print(combined_df.dtypes)  # Display current data types

Data types before conversion:
HH_ID                        int64
CUST_ID                      int64
CAR_ID                       int64
Active HH                    int64
HH Start Date               object
Phone Number                object
ZIP                          int64
State_x                     object
Country                     object
Referral Source             object
Date of Birth               object
Marital Status              object
Employment Type             object
Income                      object
Status                      object
State_y                     object
Model Year                   int64
Make                        object
Body Style                  object
Vehicle Value              float64
Annual Miles Driven          int64
Business Use                 int64
Antique Vehicle              int64
Lien                         int64
Lease                        int64
Driver Safety Discount       int64
Vehicle Safety Discount      int64
Claim Payout                 int64
6 Month Premium Amount     float64
dtype: object

In [69]:
#changing data types  of  HH Start Date, Date of Birth  from object to date 

combined_df['HH Start Date'] = pd.to_datetime(combined_df['HH Start Date'], errors='coerce')
combined_df['Date of Birth'] = pd.to_datetime(combined_df['Date of Birth'], errors='coerce')
print(combined_df.dtypes) #checking the modified data types

HH_ID                               int64
CUST_ID                             int64
CAR_ID                              int64
Active HH                           int64
HH Start Date              datetime64[ns]
Phone Number                       object
ZIP                                 int64
State_x                            object
Country                            object
Referral Source                    object
Date of Birth              datetime64[ns]
Marital Status                     object
Employment Type                    object
Income                             object
Status                             object
State_y                            object
Model Year                          int64
Make                               object
Body Style                         object
Vehicle Value                     float64
Annual Miles Driven                 int64
Business Use                        int64
Antique Vehicle                     int64
Lien                                int64
Lease                               int64
Driver Safety Discount              int64
Vehicle Safety Discount             int64
Claim Payout                        int64
6 Month Premium Amount            float64
dtype: object

In [94]:
pd.set_option('display.max_columns', None)   # Show all columns
pd.set_option('display.expand_frame_repr', False)  # Prevent line breaks
pd.set_option('display.width', 1000)  # Set a very large display width

# Assuming `df` is your DataFrame, print it
print(combined_df.head())

       HH_ID    CUST_ID  CAR_ID  Active HH HH Start Date    Phone Number   ZIP  State_x Country Referral Source Date of Birth Marital Status Employment Type Income                 Status State_y  Model Year           Make Body Style  Vehicle Value  Annual Miles Driven  Business Use  Antique Vehicle  Lien  Lease  Driver Safety Discount  Vehicle Safety Discount  Claim Payout  6 Month Premium Amount
0  219790301  801198110  844435          1    2022-11-18  (709) 379-9036  70442      OK     USA           Other    2002-11-06              D         Student      0               In Force      OK        1990  Manufacturer7     4 door       50000.00                   56             0                1     1      0                       0                        1             0               42.890000
1  219790301  801198110  844435          1    2022-11-18  (709) 379-9036  70442      OK     USA           Other    2002-11-06              D         Student      0               In Force      AL        1955  Manufacturer2     4 door         500.00                14800             0                0     1      0                       0                        0             0              452.814770
2  219790301  801198110  844435          1    2022-11-18  (709) 379-9036  70442      OK     USA           Other    2002-11-06              D         Student      0  Customer Cancellation      OH        1973  Manufacturer2        SUV         500.00                 8439             0                0     0      0                       0                        0             0              380.678401
3  219790301  281855167  410619          1    2022-11-18  (740) 565-4060  70442      OK     USA           Other    2055-06-23              D         Retired      0               In Force      OK        2019  Manufacturer5        SUV        8151.75                12136             0                0     0      1                       0                        1             0               58.887695
4  219790301  281855167  410619          1    2022-11-18  (740) 565-4060  70442      OK     USA           Other    2055-06-23              D         Retired      0               In Force      GA        2021  Manufacturer3        SUV       13460.60                89619             0                0     0      0                       0                        1             0              336.262875