In [13]:
!pip install simple-salesforce
!pip install salesforce

Requirement already satisfied: simple-salesforce in c:\users\sukan\anaconda3\lib\site-packages (1.12.6)
Requirement already satisfied: requests>=2.22.0 in c:\users\sukan\anaconda3\lib\site-packages (from simple-salesforce) (2.32.2)
Requirement already satisfied: typing-extensions in c:\users\sukan\anaconda3\lib\site-packages (from simple-salesforce) (4.11.0)
Requirement already satisfied: zeep in c:\users\sukan\anaconda3\lib\site-packages (from simple-salesforce) (4.2.1)
Requirement already satisfied: pyjwt[crypto] in c:\users\sukan\anaconda3\lib\site-packages (from simple-salesforce) (2.8.0)
Requirement already satisfied: more-itertools in c:\users\sukan\anaconda3\lib\site-packages (from simple-salesforce) (10.1.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sukan\anaconda3\lib\site-packages (from requests>=2.22.0->simple-salesforce) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sukan\anaconda3\lib\site-packages (from requests>=2.22.0->simple-salesforce) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sukan\anaconda3\lib\site-packages (from requests>=2.22.0->simple-salesforce) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sukan\anaconda3\lib\site-packages (from requests>=2.22.0->simple-salesforce) (2024.7.4)
Requirement already satisfied: cryptography>=3.4.0 in c:\users\sukan\anaconda3\lib\site-packages (from pyjwt[crypto]->simple-salesforce) (42.0.5)
Requirement already satisfied: attrs>=17.2.0 in c:\users\sukan\anaconda3\lib\site-packages (from zeep->simple-salesforce) (23.1.0)
Requirement already satisfied: isodate>=0.5.4 in c:\users\sukan\anaconda3\lib\site-packages (from zeep->simple-salesforce) (0.6.1)
Requirement already satisfied: lxml>=4.6.0 in c:\users\sukan\anaconda3\lib\site-packages (from zeep->simple-salesforce) (5.2.1)
Requirement already satisfied: platformdirs>=1.4.0 in c:\users\sukan\anaconda3\lib\site-packages (from zeep->simple-salesforce) (3.10.0)
Requirement already satisfied: requests-toolbelt>=0.7.1 in c:\users\sukan\anaconda3\lib\site-packages (from zeep->simple-salesforce) (1.0.0)
Requirement already satisfied: requests-file>=1.5.1 in c:\users\sukan\anaconda3\lib\site-packages (from zeep->simple-salesforce) (1.5.1)
Requirement already satisfied: pytz in c:\users\sukan\anaconda3\lib\site-packages (from zeep->simple-salesforce) (2024.1)
Requirement already satisfied: cffi>=1.12 in c:\users\sukan\anaconda3\lib\site-packages (from cryptography>=3.4.0->pyjwt[crypto]->simple-salesforce) (1.16.0)
Requirement already satisfied: six in c:\users\sukan\anaconda3\lib\site-packages (from isodate>=0.5.4->zeep->simple-salesforce) (1.16.0)
Requirement already satisfied: pycparser in c:\users\sukan\anaconda3\lib\site-packages (from cffi>=1.12->cryptography>=3.4.0->pyjwt[crypto]->simple-salesforce) (2.21)
Collecting salesforce
  Downloading salesforce-0.0.1.tar.gz (6.3 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: simple-salesforce in c:\users\sukan\anaconda3\lib\site-packages (from salesforce) (1.12.6)
Requirement already satisfied: requests in c:\users\sukan\anaconda3\lib\site-packages (from salesforce) (2.32.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sukan\anaconda3\lib\site-packages (from requests->salesforce) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sukan\anaconda3\lib\site-packages (from requests->salesforce) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sukan\anaconda3\lib\site-packages (from requests->salesforce) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sukan\anaconda3\lib\site-packages (from requests->salesforce) (2024.7.4)
Requirement already satisfied: typing-extensions in c:\users\sukan\anaconda3\lib\site-packages (from simple-salesforce->salesforce) (4.11.0)
Requirement already satisfied: zeep in c:\users\sukan\anaconda3\lib\site-packages (from simple-salesforce->salesforce) (4.2.1)
Requirement already satisfied: pyjwt[crypto] in c:\users\sukan\anaconda3\lib\site-packages (from simple-salesforce->salesforce) (2.8.0)
Requirement already satisfied: more-itertools in c:\users\sukan\anaconda3\lib\site-packages (from simple-salesforce->salesforce) (10.1.0)
Requirement already satisfied: cryptography>=3.4.0 in c:\users\sukan\anaconda3\lib\site-packages (from pyjwt[crypto]->simple-salesforce->salesforce) (42.0.5)
Requirement already satisfied: attrs>=17.2.0 in c:\users\sukan\anaconda3\lib\site-packages (from zeep->simple-salesforce->salesforce) (23.1.0)
Requirement already satisfied: isodate>=0.5.4 in c:\users\sukan\anaconda3\lib\site-packages (from zeep->simple-salesforce->salesforce) (0.6.1)
Requirement already satisfied: lxml>=4.6.0 in c:\users\sukan\anaconda3\lib\site-packages (from zeep->simple-salesforce->salesforce) (5.2.1)
Requirement already satisfied: platformdirs>=1.4.0 in c:\users\sukan\anaconda3\lib\site-packages (from zeep->simple-salesforce->salesforce) (3.10.0)
Requirement already satisfied: requests-toolbelt>=0.7.1 in c:\users\sukan\anaconda3\lib\site-packages (from zeep->simple-salesforce->salesforce) (1.0.0)
Requirement already satisfied: requests-file>=1.5.1 in c:\users\sukan\anaconda3\lib\site-packages (from zeep->simple-salesforce->salesforce) (1.5.1)
Requirement already satisfied: pytz in c:\users\sukan\anaconda3\lib\site-packages (from zeep->simple-salesforce->salesforce) (2024.1)
Requirement already satisfied: cffi>=1.12 in c:\users\sukan\anaconda3\lib\site-packages (from cryptography>=3.4.0->pyjwt[crypto]->simple-salesforce->salesforce) (1.16.0)
Requirement already satisfied: six in c:\users\sukan\anaconda3\lib\site-packages (from isodate>=0.5.4->zeep->simple-salesforce->salesforce) (1.16.0)
Requirement already satisfied: pycparser in c:\users\sukan\anaconda3\lib\site-packages (from cffi>=1.12->cryptography>=3.4.0->pyjwt[crypto]->simple-salesforce->salesforce) (2.21)
Building wheels for collected packages: salesforce
  Building wheel for salesforce (setup.py): started
  Building wheel for salesforce (setup.py): finished with status 'done'
  Created wheel for salesforce: filename=salesforce-0.0.1-py3-none-any.whl size=6505 sha256=de1efeb35ced05838edb8b0b651c4cbf56a7eb61b685ec52671f2d9ab034805a
  Stored in directory: c:\users\sukan\appdata\local\pip\cache\wheels\e8\31\fc\ee623965903e92750f8fd2dc4e5452112976692e08a46f18eb
Successfully built salesforce
Installing collected packages: salesforce
Successfully installed salesforce-0.0.1

In [22]:
from simple_salesforce import Salesforce
import pandas as pd

In [24]:
sfuname='rajv6903@gmail.com'
sfpwd='Sfdc@1596'
sftoken='YWh94rRBiGMTSgeLmXhI42gD'

sf=Salesforce(username=sfuname,password=sfpwd,security_token=sftoken)
print(sf)

<simple_salesforce.api.Salesforce object at 0x0000021EA5F31340>

In [146]:
response=sf.query("""
                    select Name,Site, Type, BillingCity,BillingState,BillingCountry,Phone from account
                  """)
print(response)

OrderedDict({'totalSize': 42, 'done': True, 'records': [OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002uMAdSQAW'}), 'Name': 'GenePoint', 'Site': 'US-East', 'Type': 'Customer - Channel', 'BillingCity': 'Mountain View', 'BillingState': 'CA', 'BillingCountry': None, 'Phone': '(650) 867-3450'}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002uMAdQQAW'}), 'Name': 'United Oil & Gas, UK', 'Site': 'US-Midwest', 'Type': 'Customer - Direct', 'BillingCity': None, 'BillingState': 'UK', 'BillingCountry': None, 'Phone': '+44 191 4956203'}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002uMAdRQAW'}), 'Name': 'United Oil & Gas, Singapore', 'Site': 'US-South', 'Type': 'Customer - Direct', 'BillingCity': 'Singapore', 'BillingState': 'Singapore', 'BillingCountry': None, 'Phone': '(650) 450-8810'}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002uMAdIQAW'}), 'Name': 'Edge Communications', 'Site': 'US-West', 'Type': 'Customer - Direct', 'BillingCity': 'Austin', 'BillingState': 'TX', 'BillingCountry': None, 'Phone': '(512) 757-6000'}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002uMAdJQAW'}), 'Name': 'Burlington Textiles Corp of America', 'Site': 'US-West', 'Type': 'Customer - Direct', 'BillingCity': 'Burlington', 'BillingState': 'NC', 'BillingCountry': 'USA', 'Phone': '(336) 222-7000'}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002uMAdKQAW'}), 'Name': 'Pyramid Construction Inc.', 'Site': 'US-Midwest', 'Type': 'Customer - Channel', 'BillingCity': 'Paris', 'BillingState': None, 'BillingCountry': 'France', 'Phone': '(014) 427-4427'}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002uMAdLQAW'}), 'Name': 'Dickenson plc', 'Site': 'EMEA', 'Type': 'Customer - Channel', 'BillingCity': 'Lawrence', 'BillingState': 'KS', 'BillingCountry': 'USA', 'Phone': '(785) 241-6200'}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002uMAdMQAW'}), 'Name': 'Grand Hotels & Resorts Ltd', 'Site': 'APAC', 'Type': 'Customer - Direct', 'BillingCity': 'Chicago', 'BillingState': 'IL', 'BillingCountry': None, 'Phone': '(312) 596-1000'}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002uMAdOQAW'}), 'Name': 'Express Logistics and Transport', 'Site': 'EMEA', 'Type': 'Customer - Channel', 'BillingCity': 'Portland', 'BillingState': 'OR', 'BillingCountry': None, 'Phone': '(503) 421-7800'}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002uMAdPQAW'}), 'Name': 'University of Arizona', 'Site': 'US-East', 'Type': 'Customer - Direct', 'BillingCity': 'Tucson', 'BillingState': 'AZ', 'BillingCountry': None, 'Phone': '(520) 773-9050'}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002uMAdNQAW'}), 'Name': 'United Oil & Gas Corp.', 'Site': 'US-West', 'Type': 'Customer - Direct', 'BillingCity': 'New York', 'BillingState': 'NY', 'BillingCountry': None, 'Phone': '(212) 842-5500'}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002uMAdTQAW'}), 'Name': 'sForce', 'Site': None, 'Type': None, 'BillingCity': 'San Francisco', 'BillingState': 'CA', 'BillingCountry': 'US', 'Phone': '(415) 901-7000'}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002zXzAsQAK'}), 'Name': 'Stark H', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002zXzAtQAK'}), 'Name': 'hulk M', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F000030C5STQA0'}), 'Name': 'asdffgh', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002zY14CQAS'}), 'Name': 'Avcsgd', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F0000313leEQAQ'}), 'Name': 'University of Arizona', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F0000313lgtQAA'}), 'Name': 'GenePoint', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F0000313lbfQAA'}), 'Name': 'sForce', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F000031snS3QAI'}), 'Name': 'Get Cloudy', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F000030gY1BQAU'}), 'Name': 'Contract temp 1', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F000036BtyeQAC'}), 'Name': 'Blackbeards Grog Emporium', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F000036BtrdQAC'}), 'Name': 'NewAccount2', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F000036BtqfQAC'}), 'Name': 'NewAccount1', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F000030C3vYQAS'}), 'Name': 'qwerty', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002zXyNmQAK'}), 'Name': 'hulk', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002zXyNlQAK'}), 'Name': 'Stark', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002zXygIQAS'}), 'Name': 'Stark', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002zXygJQAS'}), 'Name': 'hulk', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002zXzGCQA0'}), 'Name': 'Stark H', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002zXzGDQA0'}), 'Name': 'Dell', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002zXzGEQA0'}), 'Name': 'Hp', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002zXzGFQA0'}), 'Name': 'Lannister', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002zXzGGQA0'}), 'Name': 'Vineeth', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002zXzGHQA0'}), 'Name': 'Ashok', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002zXzGIQA0'}), 'Name': 'Deekhsitha', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002zXzGJQA0'}), 'Name': 'hulk M', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002zXzGKQA0'}), 'Name': 'Shabbir', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002zXzGLQA0'}), 'Name': 'Sandy', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002zWWkVQAW'}), 'Name': 'acc', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002zXvSrQAK'}), 'Name': 'Stark', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None}), OrderedDict({'attributes': OrderedDict({'type': 'Account', 'url': '/services/data/v59.0/sobjects/Account/0016F00002zXvSsQAK'}), 'Name': 'hulk', 'Site': None, 'Type': None, 'BillingCity': None, 'BillingState': None, 'BillingCountry': None, 'Phone': None})]})

In [148]:
df3=pd.DataFrame(response['records']).drop(labels='attributes', axis=1)
df3

,Name,Site,Type,BillingCity,BillingState,BillingCountry,Phone
0,GenePoint,US-East,Customer - Channel,Mountain View,CA,None,(650) 867-3450
1,"United Oil & Gas, UK",US-Midwest,Customer - Direct,None,UK,None,+44 191 4956203
2,"United Oil & Gas, Singapore",US-South,Customer - Direct,Singapore,Singapore,None,(650) 450-8810
3,Edge Communications,US-West,Customer - Direct,Austin,TX,None,(512) 757-6000
4,Burlington Textiles Corp of America,US-West,Customer - Direct,Burlington,NC,USA,(336) 222-7000
5,Pyramid Construction Inc.,US-Midwest,Customer - Channel,Paris,None,France,(014) 427-4427
6,Dickenson plc,EMEA,Customer - Channel,Lawrence,KS,USA,(785) 241-6200
7,Grand Hotels & Resorts Ltd,APAC,Customer - Direct,Chicago,IL,None,(312) 596-1000
8,Express Logistics and Transport,EMEA,Customer - Channel,Portland,OR,None,(503) 421-7800
9,University of Arizona,US-East,Customer - Direct,Tucson,AZ,None,(520) 773-9050
10,United Oil & Gas Corp.,US-West,Customer - Direct,New York,NY,None,(212) 842-5500
11,sForce,None,None,San Francisco,CA,US,(415) 901-7000
12,Stark H,None,None,None,None,None,None
13,hulk M,None,None,None,None,None,None
14,asdffgh,None,None,None,None,None,None
15,Avcsgd,None,None,None,None,None,None
16,University of Arizona,None,None,None,None,None,None
17,GenePoint,None,None,None,None,None,None
18,sForce,None,None,None,None,None,None
19,Get Cloudy,None,None,None,None,None,None
20,Contract temp 1,None,None,None,None,None,None
21,Blackbeards Grog Emporium,None,None,None,None,None,None
22,NewAccount2,None,None,None,None,None,None
23,NewAccount1,None,None,None,None,None,None
24,qwerty,None,None,None,None,None,None
25,hulk,None,None,None,None,None,None
26,Stark,None,None,None,None,None,None
27,Stark,None,None,None,None,None,None
28,hulk,None,None,None,None,None,None
29,Stark H,None,None,None,None,None,None
30,Dell,None,None,None,None,None,None
31,Hp,None,None,None,None,None,None
32,Lannister,None,None,None,None,None,None
33,Vineeth,None,None,None,None,None,None
34,Ashok,None,None,None,None,None,None
35,Deekhsitha,None,None,None,None,None,None
36,hulk M,None,None,None,None,None,None
37,Shabbir,None,None,None,None,None,None
38,Sandy,None,None,None,None,None,None
39,acc,None,None,None,None,None,None
40,Stark,None,None,None,None,None,None
41,hulk,None,None,None,None,None,None

In [150]:
df3.drop_duplicates()

,Name,Site,Type,BillingCity,BillingState,BillingCountry,Phone
0,GenePoint,US-East,Customer - Channel,Mountain View,CA,None,(650) 867-3450
1,"United Oil & Gas, UK",US-Midwest,Customer - Direct,None,UK,None,+44 191 4956203
2,"United Oil & Gas, Singapore",US-South,Customer - Direct,Singapore,Singapore,None,(650) 450-8810
3,Edge Communications,US-West,Customer - Direct,Austin,TX,None,(512) 757-6000
4,Burlington Textiles Corp of America,US-West,Customer - Direct,Burlington,NC,USA,(336) 222-7000
5,Pyramid Construction Inc.,US-Midwest,Customer - Channel,Paris,None,France,(014) 427-4427
6,Dickenson plc,EMEA,Customer - Channel,Lawrence,KS,USA,(785) 241-6200
7,Grand Hotels & Resorts Ltd,APAC,Customer - Direct,Chicago,IL,None,(312) 596-1000
8,Express Logistics and Transport,EMEA,Customer - Channel,Portland,OR,None,(503) 421-7800
9,University of Arizona,US-East,Customer - Direct,Tucson,AZ,None,(520) 773-9050
10,United Oil & Gas Corp.,US-West,Customer - Direct,New York,NY,None,(212) 842-5500
11,sForce,None,None,San Francisco,CA,US,(415) 901-7000
12,Stark H,None,None,None,None,None,None
13,hulk M,None,None,None,None,None,None
14,asdffgh,None,None,None,None,None,None
15,Avcsgd,None,None,None,None,None,None
16,University of Arizona,None,None,None,None,None,None
17,GenePoint,None,None,None,None,None,None
18,sForce,None,None,None,None,None,None
19,Get Cloudy,None,None,None,None,None,None
20,Contract temp 1,None,None,None,None,None,None
21,Blackbeards Grog Emporium,None,None,None,None,None,None
22,NewAccount2,None,None,None,None,None,None
23,NewAccount1,None,None,None,None,None,None
24,qwerty,None,None,None,None,None,None
25,hulk,None,None,None,None,None,None
26,Stark,None,None,None,None,None,None
30,Dell,None,None,None,None,None,None
31,Hp,None,None,None,None,None,None
32,Lannister,None,None,None,None,None,None
33,Vineeth,None,None,None,None,None,None
34,Ashok,None,None,None,None,None,None
35,Deekhsitha,None,None,None,None,None,None
37,Shabbir,None,None,None,None,None,None
38,Sandy,None,None,None,None,None,None
39,acc,None,None,None,None,None,None

In [152]:

df3.dtypes

Name              object
Site              object
Type              object
BillingCity       object
BillingState      object
BillingCountry    object
Phone             object
dtype: object

In [156]:
#checking if there exists any null values in the columns
df3.isnull().any()

Name              False
Site               True
Type               True
BillingCity        True
BillingState       True
BillingCountry     True
Phone              True
dtype: bool

In [158]:

#removing all the None values in the columns below
df3['Type']=df3['Type'].fillna('')
df3['Site']=df3['Site'].fillna('')
df3['BillingCity']=df3['BillingCity'].fillna('')
df3['BillingState']=df3['BillingState'].fillna('')
df3['BillingCountry']=df3['BillingCountry'].fillna('')
df3['Phone']=df3['Phone'].fillna('',)
#df2.fillna({})
df3

,Name,Site,Type,BillingCity,BillingState,BillingCountry,Phone
0,GenePoint,US-East,Customer - Channel,Mountain View,CA,,(650) 867-3450
1,"United Oil & Gas, UK",US-Midwest,Customer - Direct,,UK,,+44 191 4956203
2,"United Oil & Gas, Singapore",US-South,Customer - Direct,Singapore,Singapore,,(650) 450-8810
3,Edge Communications,US-West,Customer - Direct,Austin,TX,,(512) 757-6000
4,Burlington Textiles Corp of America,US-West,Customer - Direct,Burlington,NC,USA,(336) 222-7000
5,Pyramid Construction Inc.,US-Midwest,Customer - Channel,Paris,,France,(014) 427-4427
6,Dickenson plc,EMEA,Customer - Channel,Lawrence,KS,USA,(785) 241-6200
7,Grand Hotels & Resorts Ltd,APAC,Customer - Direct,Chicago,IL,,(312) 596-1000
8,Express Logistics and Transport,EMEA,Customer - Channel,Portland,OR,,(503) 421-7800
9,University of Arizona,US-East,Customer - Direct,Tucson,AZ,,(520) 773-9050
10,United Oil & Gas Corp.,US-West,Customer - Direct,New York,NY,,(212) 842-5500
11,sForce,,,San Francisco,CA,US,(415) 901-7000
12,Stark H,,,,,,
13,hulk M,,,,,,
14,asdffgh,,,,,,
15,Avcsgd,,,,,,
16,University of Arizona,,,,,,
17,GenePoint,,,,,,
18,sForce,,,,,,
19,Get Cloudy,,,,,,
20,Contract temp 1,,,,,,
21,Blackbeards Grog Emporium,,,,,,
22,NewAccount2,,,,,,
23,NewAccount1,,,,,,
24,qwerty,,,,,,
25,hulk,,,,,,
26,Stark,,,,,,
27,Stark,,,,,,
28,hulk,,,,,,
29,Stark H,,,,,,
30,Dell,,,,,,
31,Hp,,,,,,
32,Lannister,,,,,,
33,Vineeth,,,,,,
34,Ashok,,,,,,
35,Deekhsitha,,,,,,
36,hulk M,,,,,,
37,Shabbir,,,,,,
38,Sandy,,,,,,
39,acc,,,,,,
40,Stark,,,,,,
41,hulk,,,,,,

In [160]:
#splitting the type column and extracting a substr to replace the column
df3['Type']=df3['Type'].str.split(pat='-',n=1,expand=True)[1]

In [166]:
df3['Type']=df3['Type'].fillna('')

In [168]:
df3

,Name,Site,Type,BillingCity,BillingState,BillingCountry,Phone
0,GenePoint,US-East,Channel,Mountain View,CA,,(650) 867-3450
1,"United Oil & Gas, UK",US-Midwest,Direct,,UK,,+44 191 4956203
2,"United Oil & Gas, Singapore",US-South,Direct,Singapore,Singapore,,(650) 450-8810
3,Edge Communications,US-West,Direct,Austin,TX,,(512) 757-6000
4,Burlington Textiles Corp of America,US-West,Direct,Burlington,NC,USA,(336) 222-7000
5,Pyramid Construction Inc.,US-Midwest,Channel,Paris,,France,(014) 427-4427
6,Dickenson plc,EMEA,Channel,Lawrence,KS,USA,(785) 241-6200
7,Grand Hotels & Resorts Ltd,APAC,Direct,Chicago,IL,,(312) 596-1000
8,Express Logistics and Transport,EMEA,Channel,Portland,OR,,(503) 421-7800
9,University of Arizona,US-East,Direct,Tucson,AZ,,(520) 773-9050
10,United Oil & Gas Corp.,US-West,Direct,New York,NY,,(212) 842-5500
11,sForce,,,San Francisco,CA,US,(415) 901-7000
12,Stark H,,,,,,
13,hulk M,,,,,,
14,asdffgh,,,,,,
15,Avcsgd,,,,,,
16,University of Arizona,,,,,,
17,GenePoint,,,,,,
18,sForce,,,,,,
19,Get Cloudy,,,,,,
20,Contract temp 1,,,,,,
21,Blackbeards Grog Emporium,,,,,,
22,NewAccount2,,,,,,
23,NewAccount1,,,,,,
24,qwerty,,,,,,
25,hulk,,,,,,
26,Stark,,,,,,
27,Stark,,,,,,
28,hulk,,,,,,
29,Stark H,,,,,,
30,Dell,,,,,,
31,Hp,,,,,,
32,Lannister,,,,,,
33,Vineeth,,,,,,
34,Ashok,,,,,,
35,Deekhsitha,,,,,,
36,hulk M,,,,,,
37,Shabbir,,,,,,
38,Sandy,,,,,,
39,acc,,,,,,
40,Stark,,,,,,
41,hulk,,,,,,

In [170]:
df3.dtypes

Name              object
Site              object
Type              object
BillingCity       object
BillingState      object
BillingCountry    object
Phone             object
dtype: object

In [200]:
#changing the data types of the columns
df3[['Name','Site', 'Type','BillingCity','BillingState','BillingCountry','Phone']].astype(str)

,Name,Site,Type,BillingCity,BillingState,BillingCountry,Phone
0,GenePoint,US-East,Channel,Mountain View,CA,,(650) 867-3450
1,"United Oil & Gas, UK",US-Midwest,Direct,,UK,,+44 191 4956203
2,"United Oil & Gas, Singapore",US-South,Direct,Singapore,Singapore,,(650) 450-8810
3,Edge Communications,US-West,Direct,Austin,TX,,(512) 757-6000
4,Burlington Textiles Corp of America,US-West,Direct,Burlington,NC,USA,(336) 222-7000
5,Pyramid Construction Inc.,US-Midwest,Channel,Paris,,France,(014) 427-4427
6,Dickenson plc,EMEA,Channel,Lawrence,KS,USA,(785) 241-6200
7,Grand Hotels & Resorts Ltd,APAC,Direct,Chicago,IL,,(312) 596-1000
8,Express Logistics and Transport,EMEA,Channel,Portland,OR,,(503) 421-7800
9,University of Arizona,US-East,Direct,Tucson,AZ,,(520) 773-9050
10,United Oil & Gas Corp.,US-West,Direct,New York,NY,,(212) 842-5500
11,sForce,,,San Francisco,CA,US,(415) 901-7000
12,Stark H,,,,,,
13,hulk M,,,,,,
14,asdffgh,,,,,,
15,Avcsgd,,,,,,
16,University of Arizona,,,,,,
17,GenePoint,,,,,,
18,sForce,,,,,,
19,Get Cloudy,,,,,,
20,Contract temp 1,,,,,,
21,Blackbeards Grog Emporium,,,,,,
22,NewAccount2,,,,,,
23,NewAccount1,,,,,,
24,qwerty,,,,,,
25,hulk,,,,,,
26,Stark,,,,,,
27,Stark,,,,,,
28,hulk,,,,,,
29,Stark H,,,,,,
30,Dell,,,,,,
31,Hp,,,,,,
32,Lannister,,,,,,
33,Vineeth,,,,,,
34,Ashok,,,,,,
35,Deekhsitha,,,,,,
36,hulk M,,,,,,
37,Shabbir,,,,,,
38,Sandy,,,,,,
39,acc,,,,,,
40,Stark,,,,,,
41,hulk,,,,,,

In [232]:
df3['Phone']=df3['Phone'].str.replace(r'[+\./_\-() ]','', regex=True)

In [240]:
df3['Phone'] = df3['Phone'].apply(lambda x: x[3:] if x.startswith('44') else x)
df3

,Name,Site,Type,BillingCity,BillingState,BillingCountry,Phone
0,GenePoint,US-East,Channel,Mountain View,CA,,6508673450
1,"United Oil & Gas, UK",US-Midwest,Direct,,UK,,914956203
2,"United Oil & Gas, Singapore",US-South,Direct,Singapore,Singapore,,6504508810
3,Edge Communications,US-West,Direct,Austin,TX,,5127576000
4,Burlington Textiles Corp of America,US-West,Direct,Burlington,NC,USA,3362227000
5,Pyramid Construction Inc.,US-Midwest,Channel,Paris,,France,0144274427
6,Dickenson plc,EMEA,Channel,Lawrence,KS,USA,7852416200
7,Grand Hotels & Resorts Ltd,APAC,Direct,Chicago,IL,,3125961000
8,Express Logistics and Transport,EMEA,Channel,Portland,OR,,5034217800
9,University of Arizona,US-East,Direct,Tucson,AZ,,5207739050
10,United Oil & Gas Corp.,US-West,Direct,New York,NY,,2128425500
11,sForce,,,San Francisco,CA,US,4159017000
12,Stark H,,,,,,
13,hulk M,,,,,,
14,asdffgh,,,,,,
15,Avcsgd,,,,,,
16,University of Arizona,,,,,,
17,GenePoint,,,,,,
18,sForce,,,,,,
19,Get Cloudy,,,,,,
20,Contract temp 1,,,,,,
21,Blackbeards Grog Emporium,,,,,,
22,NewAccount2,,,,,,
23,NewAccount1,,,,,,
24,qwerty,,,,,,
25,hulk,,,,,,
26,Stark,,,,,,
27,Stark,,,,,,
28,hulk,,,,,,
29,Stark H,,,,,,
30,Dell,,,,,,
31,Hp,,,,,,
32,Lannister,,,,,,
33,Vineeth,,,,,,
34,Ashok,,,,,,
35,Deekhsitha,,,,,,
36,hulk M,,,,,,
37,Shabbir,,,,,,
38,Sandy,,,,,,
39,acc,,,,,,
40,Stark,,,,,,
41,hulk,,,,,,

In [242]:
df3.to_csv('output_file.csv', index=False)